name: Deploy Vue App to GitHub Pages (Development Environment)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint
        # Solo ejecutar lint en pull requests para agilizar los deploys directos
        if: github.event_name == 'pull_request'

      # Ya no necesitamos modificar la base URL porque se ajusta automáticamente según el modo
      - name: Display Vite configuration
        run: |
          echo "Usando configuración existente en vite.config.ts con mode=development"
          # Opcional: mostrar la configuración actual
          cat vite.config.ts

      # Construimos en modo development para GitHub Pages
      - name: Build project for development
        run: npm run build
        env:
          # Esta variable asegura que Node.js sepa que estamos en desarrollo
          NODE_ENV: development
          VITE_APP_BASE_URL: '/ui-parking/'

      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages (Development)
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
